version: '3'
services: 
  xmeme-rest:
    container_name: rest-server
    image: xmeme
    restart: always
    build: ./server
    ports:
      - "8081:8081"
    links: 
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes: 
      - ~/mongo/db:/data/db
    ports:
      - "27017:27017"
      