version: "3"
services: 
  rest-api:
    container_name: rest-api
    image: shikhar03stark/xmeme
    restart: always
    build: .
    ports: 
      - "8081:8081"
    links: 
      - mongo
  
  mongo:
    container_name: mongo
    image: mongo
    volumes: 
      - ~/mongo/db:/data/db
    ports:
      - "27017:27017"